[platformio]
default_envs = leonardo

[env:leonardo]
platform = atmelavr
board = leonardo
framework = arduino
monitor_speed = 115200
upload_port = COM19
monitor_port = COM18
build_flags =
    -D BRSWDIY_FW_VERSION=\"0.1.0\"
    -D BRSWDIY_PROTO_VERSION=1
    -D BRSWDIY_HW_VERSION=1