[platformio]
default_envs = leonardo_raw_incremental

[env]
platform = atmelavr
board = leonardo
framework = arduino
extra_scripts = pre:scripts/install_brswdiy_core.py
monitor_speed = 115200
upload_port = COM19
monitor_port = COM18

[env:leonardo_raw_incremental]
build_flags =
    -D BRSWDIY_FW_VERSION=\"0.1.0\"
    -D BRSWDIY_PROTO_VERSION=1
    -D BRSWDIY_HW_VERSION=1
    -D FFB_DIRECTION_ENABLED=0
    -D ENCODER_AS5600_ENABLED=0

[env:leonardo_direction_incremental]
build_flags =
    -D BRSWDIY_FW_VERSION=\"0.1.0-direction\"
    -D BRSWDIY_PROTO_VERSION=1
    -D BRSWDIY_HW_VERSION=1
    -D FFB_DIRECTION_ENABLED=1
    -D ENCODER_AS5600_ENABLED=0

[env:leonardo_raw_magnetic]
build_flags =
    -D BRSWDIY_FW_VERSION=\"0.1.0-mag\"
    -D BRSWDIY_PROTO_VERSION=1
    -D BRSWDIY_HW_VERSION=1
    -D FFB_DIRECTION_ENABLED=0
    -D ENCODER_AS5600_ENABLED=1

[env:leonardo_direction_magnetic]
build_flags =
    -D BRSWDIY_FW_VERSION=\"0.1.0-direction-mag\"
    -D BRSWDIY_PROTO_VERSION=1
    -D BRSWDIY_HW_VERSION=1
    -D FFB_DIRECTION_ENABLED=1
    -D ENCODER_AS5600_ENABLED=1
